global:
  scrape_interval: 10s  # Scrape every 10 seconds

scrape_configs:
  - job_name: 'python_app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Python app metrics exposed on port 8000

rule_files:
  - "alert.rules.yml"  # The file where your alerting rules are defined
